In [ ]:
import numpy as np
x=np.random.uniform(-150,150,100000000)
w=np.random.uniform(-7,10,100000000)
b=np.random.uniform(-10,100,1)+

In [ ]:
predict=0
for n in range(len(x)):
  predict+=w[n]*x[n]
predict+b
#took 51 seconds!

array([-12749757.53345832])

In [ ]:
pred=np.dot(x,w) + b
pred+b
#exexuted instantly

array([-12749705.51622307])

In [ ]:
import numpy as np
a=np.random.uniform(-7,-10,5)
a

array([-8.44734746, -8.36558241, -9.21072619, -8.27055624, -7.68513127])